// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package auction_house

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/desperatee/solana-go"
	ag_format "github.com/desperatee/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AuctioneerSell is the `auctioneerSell` instruction.
type AuctioneerSell struct {
	TradeStateBump      *uint8
	FreeTradeStateBump  *uint8
	ProgramAsSignerBump *uint8
	TokenSize           *uint64

	// [0] = [WRITE] wallet
	//
	// [1] = [WRITE] tokenAccount
	//
	// [2] = [] metadata
	//
	// [3] = [] authority
	//
	// [4] = [SIGNER] auctioneerAuthority
	//
	// [5] = [] auctionHouse
	//
	// [6] = [WRITE] auctionHouseFeeAccount
	//
	// [7] = [WRITE] sellerTradeState
	//
	// [8] = [WRITE] freeSellerTradeState
	//
	// [9] = [] ahAuctioneerPda
	//
	// [10] = [] programAsSigner
	//
	// [11] = [] tokenProgram
	//
	// [12] = [] systemProgram
	//
	// [13] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAuctioneerSellInstructionBuilder creates a new `AuctioneerSell` instruction builder.
func NewAuctioneerSellInstructionBuilder() *AuctioneerSell {
	nd := &AuctioneerSell{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 14),
	}
	return nd
}

// SetTradeStateBump sets the "tradeStateBump" parameter.
func (inst *AuctioneerSell) SetTradeStateBump(tradeStateBump uint8) *AuctioneerSell {
	inst.TradeStateBump = &tradeStateBump
	return inst
}

// SetFreeTradeStateBump sets the "freeTradeStateBump" parameter.
func (inst *AuctioneerSell) SetFreeTradeStateBump(freeTradeStateBump uint8) *AuctioneerSell {
	inst.FreeTradeStateBump = &freeTradeStateBump
	return inst
}

// SetProgramAsSignerBump sets the "programAsSignerBump" parameter.
func (inst *AuctioneerSell) SetProgramAsSignerBump(programAsSignerBump uint8) *AuctioneerSell {
	inst.ProgramAsSignerBump = &programAsSignerBump
	return inst
}

// SetTokenSize sets the "tokenSize" parameter.
func (inst *AuctioneerSell) SetTokenSize(tokenSize uint64) *AuctioneerSell {
	inst.TokenSize = &tokenSize
	return inst
}

// SetWalletAccount sets the "wallet" account.
func (inst *AuctioneerSell) SetWalletAccount(wallet ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(wallet).WRITE()
	return inst
}

// GetWalletAccount gets the "wallet" account.
func (inst *AuctioneerSell) GetWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetTokenAccountAccount sets the "tokenAccount" account.
func (inst *AuctioneerSell) SetTokenAccountAccount(tokenAccount ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(tokenAccount).WRITE()
	return inst
}

// GetTokenAccountAccount gets the "tokenAccount" account.
func (inst *AuctioneerSell) GetTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetMetadataAccount sets the "metadata" account.
func (inst *AuctioneerSell) SetMetadataAccount(metadata ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(metadata)
	return inst
}

// GetMetadataAccount gets the "metadata" account.
func (inst *AuctioneerSell) GetMetadataAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *AuctioneerSell) SetAuthorityAccount(authority ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(authority)
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *AuctioneerSell) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetAuctioneerAuthorityAccount sets the "auctioneerAuthority" account.
func (inst *AuctioneerSell) SetAuctioneerAuthorityAccount(auctioneerAuthority ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(auctioneerAuthority).SIGNER()
	return inst
}

// GetAuctioneerAuthorityAccount gets the "auctioneerAuthority" account.
func (inst *AuctioneerSell) GetAuctioneerAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetAuctionHouseAccount sets the "auctionHouse" account.
func (inst *AuctioneerSell) SetAuctionHouseAccount(auctionHouse ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(auctionHouse)
	return inst
}

// GetAuctionHouseAccount gets the "auctionHouse" account.
func (inst *AuctioneerSell) GetAuctionHouseAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetAuctionHouseFeeAccountAccount sets the "auctionHouseFeeAccount" account.
func (inst *AuctioneerSell) SetAuctionHouseFeeAccountAccount(auctionHouseFeeAccount ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(auctionHouseFeeAccount).WRITE()
	return inst
}

// GetAuctionHouseFeeAccountAccount gets the "auctionHouseFeeAccount" account.
func (inst *AuctioneerSell) GetAuctionHouseFeeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSellerTradeStateAccount sets the "sellerTradeState" account.
func (inst *AuctioneerSell) SetSellerTradeStateAccount(sellerTradeState ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(sellerTradeState).WRITE()
	return inst
}

// GetSellerTradeStateAccount gets the "sellerTradeState" account.
func (inst *AuctioneerSell) GetSellerTradeStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetFreeSellerTradeStateAccount sets the "freeSellerTradeState" account.
func (inst *AuctioneerSell) SetFreeSellerTradeStateAccount(freeSellerTradeState ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(freeSellerTradeState).WRITE()
	return inst
}

// GetFreeSellerTradeStateAccount gets the "freeSellerTradeState" account.
func (inst *AuctioneerSell) GetFreeSellerTradeStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetAhAuctioneerPdaAccount sets the "ahAuctioneerPda" account.
func (inst *AuctioneerSell) SetAhAuctioneerPdaAccount(ahAuctioneerPda ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(ahAuctioneerPda)
	return inst
}

// GetAhAuctioneerPdaAccount gets the "ahAuctioneerPda" account.
func (inst *AuctioneerSell) GetAhAuctioneerPdaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetProgramAsSignerAccount sets the "programAsSigner" account.
func (inst *AuctioneerSell) SetProgramAsSignerAccount(programAsSigner ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(programAsSigner)
	return inst
}

// GetProgramAsSignerAccount gets the "programAsSigner" account.
func (inst *AuctioneerSell) GetProgramAsSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *AuctioneerSell) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *AuctioneerSell) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *AuctioneerSell) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *AuctioneerSell) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetRentAccount sets the "rent" account.
func (inst *AuctioneerSell) SetRentAccount(rent ag_solanago.PublicKey) *AuctioneerSell {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *AuctioneerSell) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

func (inst AuctioneerSell) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AuctioneerSell,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AuctioneerSell) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AuctioneerSell) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.TradeStateBump == nil {
			return errors.New("TradeStateBump parameter is not set")
		}
		if inst.FreeTradeStateBump == nil {
			return errors.New("FreeTradeStateBump parameter is not set")
		}
		if inst.ProgramAsSignerBump == nil {
			return errors.New("ProgramAsSignerBump parameter is not set")
		}
		if inst.TokenSize == nil {
			return errors.New("TokenSize parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Wallet is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.TokenAccount is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Metadata is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.AuctioneerAuthority is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.AuctionHouse is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.AuctionHouseFeeAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SellerTradeState is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.FreeSellerTradeState is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.AhAuctioneerPda is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.ProgramAsSigner is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *AuctioneerSell) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AuctioneerSell")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=4]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("     TradeStateBump", *inst.TradeStateBump))
						paramsBranch.Child(ag_format.Param(" FreeTradeStateBump", *inst.FreeTradeStateBump))
						paramsBranch.Child(ag_format.Param("ProgramAsSignerBump", *inst.ProgramAsSignerBump))
						paramsBranch.Child(ag_format.Param("          TokenSize", *inst.TokenSize))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=14]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("              wallet", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("               token", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("            metadata", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("           authority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta(" auctioneerAuthority", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("        auctionHouse", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("     auctionHouseFee", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("    sellerTradeState", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("freeSellerTradeState", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("     ahAuctioneerPda", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("     programAsSigner", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("        tokenProgram", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("       systemProgram", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("                rent", inst.AccountMetaSlice.Get(13)))
					})
				})
		})
}

func (obj AuctioneerSell) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `TradeStateBump` param:
	err = encoder.Encode(obj.TradeStateBump)
	if err != nil {
		return err
	}
	// Serialize `FreeTradeStateBump` param:
	err = encoder.Encode(obj.FreeTradeStateBump)
	if err != nil {
		return err
	}
	// Serialize `ProgramAsSignerBump` param:
	err = encoder.Encode(obj.ProgramAsSignerBump)
	if err != nil {
		return err
	}
	// Serialize `TokenSize` param:
	err = encoder.Encode(obj.TokenSize)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AuctioneerSell) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `TradeStateBump`:
	err = decoder.Decode(&obj.TradeStateBump)
	if err != nil {
		return err
	}
	// Deserialize `FreeTradeStateBump`:
	err = decoder.Decode(&obj.FreeTradeStateBump)
	if err != nil {
		return err
	}
	// Deserialize `ProgramAsSignerBump`:
	err = decoder.Decode(&obj.ProgramAsSignerBump)
	if err != nil {
		return err
	}
	// Deserialize `TokenSize`:
	err = decoder.Decode(&obj.TokenSize)
	if err != nil {
		return err
	}
	return nil
}

// NewAuctioneerSellInstruction declares a new AuctioneerSell instruction with the provided parameters and accounts.
func NewAuctioneerSellInstruction(
	// Parameters:
	tradeStateBump uint8,
	freeTradeStateBump uint8,
	programAsSignerBump uint8,
	tokenSize uint64,
	// Accounts:
	wallet ag_solanago.PublicKey,
	tokenAccount ag_solanago.PublicKey,
	metadata ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	auctioneerAuthority ag_solanago.PublicKey,
	auctionHouse ag_solanago.PublicKey,
	auctionHouseFeeAccount ag_solanago.PublicKey,
	sellerTradeState ag_solanago.PublicKey,
	freeSellerTradeState ag_solanago.PublicKey,
	ahAuctioneerPda ag_solanago.PublicKey,
	programAsSigner ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *AuctioneerSell {
	return NewAuctioneerSellInstructionBuilder().
		SetTradeStateBump(tradeStateBump).
		SetFreeTradeStateBump(freeTradeStateBump).
		SetProgramAsSignerBump(programAsSignerBump).
		SetTokenSize(tokenSize).
		SetWalletAccount(wallet).
		SetTokenAccountAccount(tokenAccount).
		SetMetadataAccount(metadata).
		SetAuthorityAccount(authority).
		SetAuctioneerAuthorityAccount(auctioneerAuthority).
		SetAuctionHouseAccount(auctionHouse).
		SetAuctionHouseFeeAccountAccount(auctionHouseFeeAccount).
		SetSellerTradeStateAccount(sellerTradeState).
		SetFreeSellerTradeStateAccount(freeSellerTradeState).
		SetAhAuctioneerPdaAccount(ahAuctioneerPda).
		SetProgramAsSignerAccount(programAsSigner).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent)
}
