// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package auction_house

import ag_binary "github.com/gagliardetto/binary"

type AuthorityScope ag_binary.BorshEnum

const (
	AuthorityScopeDeposit AuthorityScope = iota
	AuthorityScopeBuy
	AuthorityScopePublicBuy
	AuthorityScopeExecuteSale
	AuthorityScopeSell
	AuthorityScopeCancel
	AuthorityScopeWithdraw
)

func (value AuthorityScope) String() string {
	switch value {
	case AuthorityScopeDeposit:
		return "Deposit"
	case AuthorityScopeBuy:
		return "Buy"
	case AuthorityScopePublicBuy:
		return "PublicBuy"
	case AuthorityScopeExecuteSale:
		return "ExecuteSale"
	case AuthorityScopeSell:
		return "Sell"
	case AuthorityScopeCancel:
		return "Cancel"
	case AuthorityScopeWithdraw:
		return "Withdraw"
	default:
		return ""
	}
}

type BidType ag_binary.BorshEnum

const (
	BidTypePublicSale BidType = iota
	BidTypePrivateSale
	BidTypeAuctioneerPublicSale
	BidTypeAuctioneerPrivateSale
)

func (value BidType) String() string {
	switch value {
	case BidTypePublicSale:
		return "PublicSale"
	case BidTypePrivateSale:
		return "PrivateSale"
	case BidTypeAuctioneerPublicSale:
		return "AuctioneerPublicSale"
	case BidTypeAuctioneerPrivateSale:
		return "AuctioneerPrivateSale"
	default:
		return ""
	}
}

type ListingType ag_binary.BorshEnum

const (
	ListingTypeSell ListingType = iota
	ListingTypeAuctioneerSell
)

func (value ListingType) String() string {
	switch value {
	case ListingTypeSell:
		return "Sell"
	case ListingTypeAuctioneerSell:
		return "AuctioneerSell"
	default:
		return ""
	}
}

type PurchaseType ag_binary.BorshEnum

const (
	PurchaseTypeExecuteSale PurchaseType = iota
	PurchaseTypeAuctioneerExecuteSale
)

func (value PurchaseType) String() string {
	switch value {
	case PurchaseTypeExecuteSale:
		return "ExecuteSale"
	case PurchaseTypeAuctioneerExecuteSale:
		return "AuctioneerExecuteSale"
	default:
		return ""
	}
}

type CancelType ag_binary.BorshEnum

const (
	CancelTypeCancel CancelType = iota
	CancelTypeAuctioneerCancel
)

func (value CancelType) String() string {
	switch value {
	case CancelTypeCancel:
		return "Cancel"
	case CancelTypeAuctioneerCancel:
		return "AuctioneerCancel"
	default:
		return ""
	}
}
