// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package me_launchpad

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/RoboticAgile/solana-go"
	ag_format "github.com/RoboticAgile/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Thaw is the `thaw` instruction.
type Thaw struct {

	// [0] = [WRITE, SIGNER] payer
	//
	// [1] = [WRITE] assetOwner
	//
	// [2] = [WRITE] freezeState
	//
	// [3] = [] candyMachine
	//
	// [4] = [] assetMint
	//
	// [5] = [WRITE] assetToken
	//
	// [6] = [] assetMasterEdition
	//
	// [7] = [] tokenMetadataProgram
	//
	// [8] = [] systemProgram
	//
	// [9] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewThawInstructionBuilder creates a new `Thaw` instruction builder.
func NewThawInstructionBuilder() *Thaw {
	nd := &Thaw{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetPayerAccount sets the "payer" account.
func (inst *Thaw) SetPayerAccount(payer ag_solanago.PublicKey) *Thaw {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *Thaw) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAssetOwnerAccount sets the "assetOwner" account.
func (inst *Thaw) SetAssetOwnerAccount(assetOwner ag_solanago.PublicKey) *Thaw {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(assetOwner).WRITE()
	return inst
}

// GetAssetOwnerAccount gets the "assetOwner" account.
func (inst *Thaw) GetAssetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetFreezeStateAccount sets the "freezeState" account.
func (inst *Thaw) SetFreezeStateAccount(freezeState ag_solanago.PublicKey) *Thaw {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(freezeState).WRITE()
	return inst
}

// GetFreezeStateAccount gets the "freezeState" account.
func (inst *Thaw) GetFreezeStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetCandyMachineAccount sets the "candyMachine" account.
func (inst *Thaw) SetCandyMachineAccount(candyMachine ag_solanago.PublicKey) *Thaw {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(candyMachine)
	return inst
}

// GetCandyMachineAccount gets the "candyMachine" account.
func (inst *Thaw) GetCandyMachineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetAssetMintAccount sets the "assetMint" account.
func (inst *Thaw) SetAssetMintAccount(assetMint ag_solanago.PublicKey) *Thaw {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(assetMint)
	return inst
}

// GetAssetMintAccount gets the "assetMint" account.
func (inst *Thaw) GetAssetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetAssetTokenAccount sets the "assetToken" account.
func (inst *Thaw) SetAssetTokenAccount(assetToken ag_solanago.PublicKey) *Thaw {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(assetToken).WRITE()
	return inst
}

// GetAssetTokenAccount gets the "assetToken" account.
func (inst *Thaw) GetAssetTokenAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetAssetMasterEditionAccount sets the "assetMasterEdition" account.
func (inst *Thaw) SetAssetMasterEditionAccount(assetMasterEdition ag_solanago.PublicKey) *Thaw {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(assetMasterEdition)
	return inst
}

// GetAssetMasterEditionAccount gets the "assetMasterEdition" account.
func (inst *Thaw) GetAssetMasterEditionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenMetadataProgramAccount sets the "tokenMetadataProgram" account.
func (inst *Thaw) SetTokenMetadataProgramAccount(tokenMetadataProgram ag_solanago.PublicKey) *Thaw {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenMetadataProgram)
	return inst
}

// GetTokenMetadataProgramAccount gets the "tokenMetadataProgram" account.
func (inst *Thaw) GetTokenMetadataProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *Thaw) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *Thaw {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *Thaw) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *Thaw) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *Thaw {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *Thaw) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst Thaw) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Thaw,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Thaw) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Thaw) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.AssetOwner is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.FreezeState is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.CandyMachine is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.AssetMint is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.AssetToken is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.AssetMasterEdition is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenMetadataProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *Thaw) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Thaw")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("               payer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("          assetOwner", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("         freezeState", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("        candyMachine", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("           assetMint", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("          assetToken", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("  assetMasterEdition", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("tokenMetadataProgram", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("       systemProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("        tokenProgram", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj Thaw) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *Thaw) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewThawInstruction declares a new Thaw instruction with the provided parameters and accounts.
func NewThawInstruction(
	// Accounts:
	payer ag_solanago.PublicKey,
	assetOwner ag_solanago.PublicKey,
	freezeState ag_solanago.PublicKey,
	candyMachine ag_solanago.PublicKey,
	assetMint ag_solanago.PublicKey,
	assetToken ag_solanago.PublicKey,
	assetMasterEdition ag_solanago.PublicKey,
	tokenMetadataProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *Thaw {
	return NewThawInstructionBuilder().
		SetPayerAccount(payer).
		SetAssetOwnerAccount(assetOwner).
		SetFreezeStateAccount(freezeState).
		SetCandyMachineAccount(candyMachine).
		SetAssetMintAccount(assetMint).
		SetAssetTokenAccount(assetToken).
		SetAssetMasterEditionAccount(assetMasterEdition).
		SetTokenMetadataProgramAccount(tokenMetadataProgram).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram)
}
