// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package me_launchpad

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/RoboticAgile/solana-go"
	ag_format "github.com/RoboticAgile/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateFreezeState is the `updateFreezeState` instruction.
type UpdateFreezeState struct {
	Args *UpdateFreezeStateArgs

	// [0] = [WRITE, SIGNER] authority
	//
	// [1] = [WRITE] freezeState
	//
	// [2] = [] candyMachine
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateFreezeStateInstructionBuilder creates a new `UpdateFreezeState` instruction builder.
func NewUpdateFreezeStateInstructionBuilder() *UpdateFreezeState {
	nd := &UpdateFreezeState{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetArgs sets the "args" parameter.
func (inst *UpdateFreezeState) SetArgs(args UpdateFreezeStateArgs) *UpdateFreezeState {
	inst.Args = &args
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *UpdateFreezeState) SetAuthorityAccount(authority ag_solanago.PublicKey) *UpdateFreezeState {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).WRITE().SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *UpdateFreezeState) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetFreezeStateAccount sets the "freezeState" account.
func (inst *UpdateFreezeState) SetFreezeStateAccount(freezeState ag_solanago.PublicKey) *UpdateFreezeState {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(freezeState).WRITE()
	return inst
}

// GetFreezeStateAccount gets the "freezeState" account.
func (inst *UpdateFreezeState) GetFreezeStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetCandyMachineAccount sets the "candyMachine" account.
func (inst *UpdateFreezeState) SetCandyMachineAccount(candyMachine ag_solanago.PublicKey) *UpdateFreezeState {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(candyMachine)
	return inst
}

// GetCandyMachineAccount gets the "candyMachine" account.
func (inst *UpdateFreezeState) GetCandyMachineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *UpdateFreezeState) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *UpdateFreezeState {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *UpdateFreezeState) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst UpdateFreezeState) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateFreezeState,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateFreezeState) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateFreezeState) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Args == nil {
			return errors.New("Args parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.FreezeState is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.CandyMachine is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *UpdateFreezeState) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateFreezeState")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Args", *inst.Args))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("    authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("  freezeState", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta(" candyMachine", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj UpdateFreezeState) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Args` param:
	err = encoder.Encode(obj.Args)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdateFreezeState) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Args`:
	err = decoder.Decode(&obj.Args)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateFreezeStateInstruction declares a new UpdateFreezeState instruction with the provided parameters and accounts.
func NewUpdateFreezeStateInstruction(
	// Parameters:
	args UpdateFreezeStateArgs,
	// Accounts:
	authority ag_solanago.PublicKey,
	freezeState ag_solanago.PublicKey,
	candyMachine ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *UpdateFreezeState {
	return NewUpdateFreezeStateInstructionBuilder().
		SetArgs(args).
		SetAuthorityAccount(authority).
		SetFreezeStateAccount(freezeState).
		SetCandyMachineAccount(candyMachine).
		SetSystemProgramAccount(systemProgram)
}
