// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package nft_candy_machine

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/desperatee/solana-go"
	ag_format "github.com/desperatee/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// MintV5 is the `mintV5` instruction.
type MintV5 struct {
	Proof  *[][32]uint8
	Expect *uint64

	// [0] = [WRITE] candyMachine
	//
	// [1] = [WRITE, SIGNER] payer
	//
	// [2] = [WRITE] wallet
	//
	// [3] = [WRITE] wallet2
	//
	// [4] = [WRITE] metadata
	//
	// [5] = [WRITE, SIGNER] mint
	//
	// [6] = [WRITE] associated
	//
	// [7] = [WRITE] masterEdition
	//
	// [8] = [WRITE] totalMints
	//
	// [9] = [] associatedTokenProgram
	//
	// [10] = [] tokenMetadataProgram
	//
	// [11] = [] tokenProgram
	//
	// [12] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewMintV5InstructionBuilder creates a new `MintV5` instruction builder.
func NewMintV5InstructionBuilder() *MintV5 {
	nd := &MintV5{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 16),
	}
	return nd
}

// SetProof sets the "proof" parameter.
func (inst *MintV5) SetProof(proof [][32]uint8) *MintV5 {
	inst.Proof = &proof
	return inst
}

// SetExpect sets the "expect" parameter.
func (inst *MintV5) SetExpect(expect uint64) *MintV5 {
	inst.Expect = &expect
	return inst
}

// SetCandyMachineAccount sets the "candyMachine" account.
func (inst *MintV5) SetCandyMachineAccount(candyMachine ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(candyMachine).WRITE()
	return inst
}

// GetCandyMachineAccount gets the "candyMachine" account.
func (inst *MintV5) GetCandyMachineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPayerAccount sets the "payer" account.
func (inst *MintV5) SetPayerAccount(payer ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *MintV5) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetWalletAccount sets the "wallet" account.
func (inst *MintV5) SetWalletAccount(wallet ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(wallet).WRITE()
	return inst
}

// GetWalletAccount gets the "wallet" account.
func (inst *MintV5) GetWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetWallet2Account sets the "wallet2" account.
func (inst *MintV5) SetWallet2Account(wallet2 ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(wallet2).WRITE()
	return inst
}

// GetWallet2Account gets the "wallet2" account.
func (inst *MintV5) GetWallet2Account() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetMetadataAccount sets the "metadata" account.
func (inst *MintV5) SetMetadataAccount(metadata ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(metadata).WRITE()
	return inst
}

// GetMetadataAccount gets the "metadata" account.
func (inst *MintV5) GetMetadataAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetMintAccount sets the "mint" account.
func (inst *MintV5) SetMintAccount(mint ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(mint).WRITE().SIGNER()
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *MintV5) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetAssociatedAccount sets the "associated" account.
func (inst *MintV5) SetAssociatedAccount(associated ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(associated).WRITE()
	return inst
}

// GetAssociatedAccount gets the "associated" account.
func (inst *MintV5) GetAssociatedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetMasterEditionAccount sets the "masterEdition" account.
func (inst *MintV5) SetMasterEditionAccount(masterEdition ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(masterEdition).WRITE()
	return inst
}

// GetMasterEditionAccount gets the "masterEdition" account.
func (inst *MintV5) GetMasterEditionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTotalMintsAccount sets the "totalMints" account.
func (inst *MintV5) SetTotalMintsAccount(totalMints ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(totalMints).WRITE()
	return inst
}

// GetTotalMintsAccount gets the "totalMints" account.
func (inst *MintV5) GetTotalMintsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *MintV5) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *MintV5) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetTokenMetadataProgramAccount sets the "tokenMetadataProgram" account.
func (inst *MintV5) SetTokenMetadataProgramAccount(tokenMetadataProgram ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(tokenMetadataProgram)
	return inst
}

// GetTokenMetadataProgramAccount gets the "tokenMetadataProgram" account.
func (inst *MintV5) GetTokenMetadataProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *MintV5) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *MintV5) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *MintV5) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *MintV5 {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *MintV5) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

func (inst *MintV5) SetAdditionalAccounts(pk []ag_solanago.AccountMeta) *MintV5 {
	amount := len(pk)
	if amount == 0 {
		return inst
	}
	for i := 0; i < amount; i++ {
		inst.AccountMetaSlice[13+i] = &pk[i]
	}
	return inst
}

func (inst MintV5) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_MintV5,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst MintV5) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *MintV5) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Proof == nil {
			return errors.New("Proof parameter is not set")
		}
		if inst.Expect == nil {
			return errors.New("Expect parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.CandyMachine is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Wallet is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Wallet2 is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Metadata is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Associated is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.MasterEdition is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TotalMints is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.TokenMetadataProgram is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *MintV5) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("MintV5")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param(" Proof", *inst.Proof))
						paramsBranch.Child(ag_format.Param("Expect", *inst.Expect))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=13]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          candyMachine", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                 payer", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                wallet", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("               wallet2", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("              metadata", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("                  mint", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("            associated", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("         masterEdition", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("            totalMints", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("associatedTokenProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("  tokenMetadataProgram", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("         systemProgram", inst.AccountMetaSlice.Get(12)))
					})
				})
		})
}

func (obj MintV5) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Proof` param:
	err = encoder.Encode(obj.Proof)
	if err != nil {
		return err
	}
	// Serialize `Expect` param:
	err = encoder.Encode(obj.Expect)
	if err != nil {
		return err
	}
	return nil
}
func (obj *MintV5) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Proof`:
	err = decoder.Decode(&obj.Proof)
	if err != nil {
		return err
	}
	// Deserialize `Expect`:
	err = decoder.Decode(&obj.Expect)
	if err != nil {
		return err
	}
	return nil
}

// NewMintV5Instruction declares a new MintV5 instruction with the provided parameters and accounts.
func NewMintV5Instruction(
	// Parameters:
	proof [][32]uint8,
	expect uint64,
	// Accounts:
	candyMachine ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	wallet ag_solanago.PublicKey,
	wallet2 ag_solanago.PublicKey,
	metadata ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	associated ag_solanago.PublicKey,
	masterEdition ag_solanago.PublicKey,
	totalMints ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	tokenMetadataProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	additionalAccounts []ag_solanago.AccountMeta) *MintV5 {
	return NewMintV5InstructionBuilder().
		SetProof(proof).
		SetExpect(expect).
		SetCandyMachineAccount(candyMachine).
		SetPayerAccount(payer).
		SetWalletAccount(wallet).
		SetWallet2Account(wallet2).
		SetMetadataAccount(metadata).
		SetMintAccount(mint).
		SetAssociatedAccount(associated).
		SetMasterEditionAccount(masterEdition).
		SetTotalMintsAccount(totalMints).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetTokenMetadataProgramAccount(tokenMetadataProgram).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetAdditionalAccounts(additionalAccounts)
}
