// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package gumdrop

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/desperatee/solana-go"
	ag_format "github.com/desperatee/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CloseDistributor is the `closeDistributor` instruction.
type CloseDistributor struct {
	Bump       *uint8
	WalletBump *uint8

	// [0] = [SIGNER] base
	//
	// [1] = [WRITE] distributor
	//
	// [2] = [WRITE] distributorWallet
	//
	// [3] = [] receiver
	//
	// [4] = [] systemProgram
	//
	// [5] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCloseDistributorInstructionBuilder creates a new `CloseDistributor` instruction builder.
func NewCloseDistributorInstructionBuilder() *CloseDistributor {
	nd := &CloseDistributor{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetBump sets the "bump" parameter.
func (inst *CloseDistributor) SetBump(bump uint8) *CloseDistributor {
	inst.Bump = &bump
	return inst
}

// SetWalletBump sets the "walletBump" parameter.
func (inst *CloseDistributor) SetWalletBump(walletBump uint8) *CloseDistributor {
	inst.WalletBump = &walletBump
	return inst
}

// SetBaseAccount sets the "base" account.
func (inst *CloseDistributor) SetBaseAccount(base ag_solanago.PublicKey) *CloseDistributor {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(base).SIGNER()
	return inst
}

// GetBaseAccount gets the "base" account.
func (inst *CloseDistributor) GetBaseAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetDistributorAccount sets the "distributor" account.
func (inst *CloseDistributor) SetDistributorAccount(distributor ag_solanago.PublicKey) *CloseDistributor {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(distributor).WRITE()
	return inst
}

// GetDistributorAccount gets the "distributor" account.
func (inst *CloseDistributor) GetDistributorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetDistributorWalletAccount sets the "distributorWallet" account.
func (inst *CloseDistributor) SetDistributorWalletAccount(distributorWallet ag_solanago.PublicKey) *CloseDistributor {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(distributorWallet).WRITE()
	return inst
}

// GetDistributorWalletAccount gets the "distributorWallet" account.
func (inst *CloseDistributor) GetDistributorWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetReceiverAccount sets the "receiver" account.
func (inst *CloseDistributor) SetReceiverAccount(receiver ag_solanago.PublicKey) *CloseDistributor {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(receiver)
	return inst
}

// GetReceiverAccount gets the "receiver" account.
func (inst *CloseDistributor) GetReceiverAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *CloseDistributor) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CloseDistributor {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *CloseDistributor) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *CloseDistributor) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *CloseDistributor {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *CloseDistributor) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst CloseDistributor) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CloseDistributor,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CloseDistributor) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CloseDistributor) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Bump == nil {
			return errors.New("Bump parameter is not set")
		}
		if inst.WalletBump == nil {
			return errors.New("WalletBump parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Base is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Distributor is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.DistributorWallet is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Receiver is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *CloseDistributor) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CloseDistributor")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("      Bump", *inst.Bump))
						paramsBranch.Child(ag_format.Param("WalletBump", *inst.WalletBump))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("             base", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("      distributor", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("distributorWallet", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("         receiver", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("    systemProgram", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("     tokenProgram", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj CloseDistributor) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	// Serialize `WalletBump` param:
	err = encoder.Encode(obj.WalletBump)
	if err != nil {
		return err
	}
	return nil
}
func (obj *CloseDistributor) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	// Deserialize `WalletBump`:
	err = decoder.Decode(&obj.WalletBump)
	if err != nil {
		return err
	}
	return nil
}

// NewCloseDistributorInstruction declares a new CloseDistributor instruction with the provided parameters and accounts.
func NewCloseDistributorInstruction(
	// Parameters:
	bump uint8,
	walletBump uint8,
	// Accounts:
	base ag_solanago.PublicKey,
	distributor ag_solanago.PublicKey,
	distributorWallet ag_solanago.PublicKey,
	receiver ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *CloseDistributor {
	return NewCloseDistributorInstructionBuilder().
		SetBump(bump).
		SetWalletBump(walletBump).
		SetBaseAccount(base).
		SetDistributorAccount(distributor).
		SetDistributorWalletAccount(distributorWallet).
		SetReceiverAccount(receiver).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram)
}
